//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrambler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScramblerMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScramblerMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scrambler.ScramblerMessages", typeof(ScramblerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter destination path of output XML:.
        /// </summary>
        internal static string enter_dest_path {
            get {
                return ResourceManager.GetString("enter_dest_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter node name to scramble:.
        /// </summary>
        internal static string enter_nodename {
            get {
                return ResourceManager.GetString("enter_nodename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter node type:.
        /// </summary>
        internal static string enter_nodetype {
            get {
                return ResourceManager.GetString("enter_nodetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter source path of input XML:.
        /// </summary>
        internal static string enter_source_path {
            get {
                return ResourceManager.GetString("enter_source_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s an invalid node name. Plese come up with a valid name.
        /// </summary>
        internal static string invalid_nodename {
            get {
                return ResourceManager.GetString("invalid_nodename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That seems to be an invlid node name, let&apos;s try again..
        /// </summary>
        internal static string invalid_nodename2 {
            get {
                return ResourceManager.GetString("invalid_nodename2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s an invalid node type. Please enter something from the options:.
        /// </summary>
        internal static string invalid_nodetype {
            get {
                return ResourceManager.GetString("invalid_nodetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was an invalid option, let&apos;s try again.
        /// </summary>
        internal static string invalid_option {
            get {
                return ResourceManager.GetString("invalid_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered invalid path.
        /// </summary>
        internal static string invalid_path {
            get {
                return ResourceManager.GetString("invalid_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That seems to be an invalid file path, let&apos;s try again:.
        /// </summary>
        internal static string invalid_path2 {
            get {
                return ResourceManager.GetString("invalid_path2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enter another node name.
        /// </summary>
        internal static string nodename_option {
            get {
                return ResourceManager.GetString("nodename_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traversing the XML and scrambling node values....
        /// </summary>
        internal static string scrambling_progress {
            get {
                return ResourceManager.GetString("scrambling_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of this node have been scrambled.
        /// </summary>
        internal static string scrambling_success {
            get {
                return ResourceManager.GetString("scrambling_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSN.
        /// </summary>
        internal static string ssn {
            get {
                return ResourceManager.GetString("ssn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML generated successfully.
        /// </summary>
        internal static string xml_generation_success {
            get {
                return ResourceManager.GetString("xml_generation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
